
// import { Inter } from "next/font/google";
// import StyledComponentsRegistry from '@/lib/registry';
// import "./globals.css";
// import Header from "@/components/common/Header";
// import Footer from "@/components/common/Footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header>Header</Header>
//         <StyledComponentsRegistry>{children} </StyledComponentsRegistry>
//         <Footer>Footer</Footer>
//       </body>
//     </html>
//   );
// }
// app/layout.js

import StyledComponentsRegistry from '@/lib/registry';
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import ReactQueryProvider from '@/components/common/ReactQueryProvider';
import AuthLayout from '@/components/common/AuthLayout';

export const metadata = {
  title: "Find Your Best Study Mate",
  description: "Find Your Best Study Mate, a platform for finding study partners. Find your best study mate and study together.",
  openGraph: {
    title: 'Find Your Best Study Mate',
      description: "Find Your Best Study Mate, a platform for finding study partners. Find your best study mate and study together.",
  },
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <AuthLayout>
            <Header>Header</Header>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            <Footer>Footer</Footer>
          </AuthLayout>
        </ReactQueryProvider>
      </body>
    </html>
  );
};


